apiVersion: apps/v1
kind: Deployment
metadata:
  name: harsh
  labels:
    app: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - name: harsh
        image: harsh3897/java:latest
        ports:
        - containerPort: 8080
          protocol: TCP
